### ISSUE TITLE
readWQMdat.m and single data point burst

### ISSUE THREAD

**Issue by sspagnol** [aodn/imos-toolbox#250]
In readWQMdat.m, if when calculating burst times you have a single data point burst then code loop to work out burst intervals would fail (line 245, diff of array with only one element), as a quick fix modified loop starting line 243.

  for i=1:nBurst
      timeBurst = time(iBurst(i):iBurst(i+1)-1);
      if numel(timeBurst)>1
          sampleIntervalInBurst(i) = median(diff(timeBurst*24*3600));
          firstTimeBurst(i) = timeBurst(1);
          durationBurst(i) = (timeBurst(end) - timeBurst(1))*24*3600;
      end
  end

Assumes you don't have so many single point bursts that would affect the sample_data.meta.instrument_sample_interval (and other) calculations.

As a side note couldn't work out how to comment on code like I used to on google code, if there is a way let me know.

Simon.

**Comment by ggalibert** [comment]
Thanks for this @sspagnol . Could you please send me a sample file for this case?

I don't think you can comment on the code in github like we could do in google-code. When you have a fix ready like this one, the best is to clone the repo, make the modification on you local copy, create a branch, add the modified file, commit and push the branch. Then on the github repo web page you can create a pull request for that branch that I will review so that it is then merged to the master branch.

Careful when including matlab code where Markdown is supported. The star character is for example a reserved Markdown character. You can use the Markdown special features for code with syntax highlighting though https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown :
```matlab
  for i=1:nBurst
      timeBurst = time(iBurst(i):iBurst(i+1)-1);
      if numel(timeBurst)>1
          sampleIntervalInBurst(i) = median(diff(timeBurst*24*3600));
          firstTimeBurst(i) = timeBurst(1);
          durationBurst(i) = (timeBurst(end) - timeBurst(1))*24*3600;
      end
  end
```

**Comment by sspagnol** [comment]
Hi Guillaume, short file with one burst having only one data point.

Going to have to read the github help pages to work out this new pull
request stuff.

Thanks,
Simon.

**Comment by ggalibert** [comment]
This has been fixed in this commit : https://github.com/aodn/imos-toolbox/commit/77d890b7b41be77590b0982e529b5a1acb72185f
