### ISSUE TITLE
Import AWAC .wpr file - slow

### ISSUE THREAD

**Issue by FelicityMc** [aodn/imos-toolbox#429]
Importing AWAC - waves and/or currents - takes in excess of 2-3 hours. Sometimes falls over prior to completion.

**Comment by ggalibert** [comment]
Has been fixed in [v2.5.26](https://github.com/aodn/imos-toolbox/releases/tag/v2.5.26) of the toolbox. In particular by:

-Nortek binary files are not read byte by byte in a while loop anymore. The structure of the file is inferred first and then file is read section by section. c673fb9
-Nortek binary sectors parsing has been vectorised so that all sectors of a same type are being parsed at once. Improves greatly parsers performances. 49c6fa2
-Added better support for HR AquadoppProfiler metadata. Simplified the way Status uint8 is read (in particular for orientation information). Same with other uint16 similar data. b66f4e6

Those files should now be read in less than a couple of minutes. 

Note that these files are quite big and it is important that the 64bit version of the toolbox is ran with sufficient RAM memory (I currently use 16Gb which I found is a minimum to handle biggest files).
