### ISSUE TITLE
Option to not display QC plots when running imosToolbox in auto mode

### ISSUE THREAD

**Issue by sspagnol** [aodn/imos-toolbox#438]
Is there an option (or can one be done) to not display QC plots when running imosToolbox in auto mode. I don't know how this would affect the fastSaveas code. Perhaps if in auto mode had to be slow method of saving image?

**Comment by ggalibert** [comment]
Unfortunately fastSaveas uses screencapture which forces an invisible figure to be visible in order to save it.
In the past I had chosen to use screencapture after difficulties with being able to save plots in a consistent manner across platforms.
See https://github.com/aodn/imos-toolbox/commit/95acf6b7d26ca6f49dc2ca8c08fc6cf50dd051ca .

**Comment by ggalibert** [comment]
Would more recent versions of Matlab be any better at saving figures?
-Consistent between what you see on your screen and what you get in the .png file,
-Fast.

**Comment by ggalibert** [comment]
Commits https://github.com/aodn/imos-toolbox/commit/ca1020c6e4a036d83a1e8d8bd40f1c3c293f7868 and https://github.com/aodn/imos-toolbox/commit/53f39974a13e01dd1cd75959f193dca2eef73129 implemented in [v2.5.30](https://github.com/aodn/imos-toolbox/releases/tag/v2.5.30) fix the issue. 

Discovered [hgexport](https://au.mathworks.com/help/matlab/ref/hgexport.html) which seems to be the best native Matlab function at saving figures to file. The is the function used to save a figure when clicking on the icon "Save as" on any figure.
