### ISSUE TITLE
crop png files

### ISSUE THREAD

**Issue by anaredd** [aodn/imos-toolbox#454]
When proccesing data from the newest toolbox verison (2.5.28 - PCWIN64) using both windows10 and windows 7, the saved png files are cropped (see example attached), therefore some of the pannels (in this case temp) and the legend are left out from the figure
 
![imos_anmn-sa_ga19k_fv01_20170518t070409z_line_c-20170710t053857z](https://user-images.githubusercontent.com/17558169/28004634-1c815fe8-6585-11e7-9c6c-33f6cabc417a.png)

**Comment by ggalibert** [comment]
Can you please tell me more about your screen configuration?
- How many screens and in which positions.
- What resolution on all available screens.

I have had a few feedback on this problem and yet never managed to re-create it on my side.

**Comment by anaredd** [comment]
Both PM and myself have the same problem.  I am using two screens, the main landscape (2560x1440) and the other one portrait orientation (1080x1920), but even if I disconnect the second screen and use only the main one, the saved figures look exactly the same.

**Comment by anaredd** [comment]
Also, I am using windows 10 and matlab version 2017a and Paul is using windows 7 and matlab version 2016b

**Comment by mrbeck85** [comment]
Hi everyone - I currently am having the same issue, and realised we had run into this problem at AIMS Townsville before. Old thread here, but no solution posted there either:
https://github.com/aodn/imos-toolbox/issues/412

I ended up emailing Simon Spagnol about it the last time this came up and he isolated the problem. I've copied some of his email text here, but the gist is that the toolbox is using a screenshot-equivalent instead of the built-in MATLAB image saving process in order to save processing power/time (I think). Simon or Guillaime will need to comment/confirm about what exactly is going on.

Text from Simon email:
> Long story first: in Matlab there is the slow way and the fast way save images. imosToolbox uses the fast way (basically finds the handle of figure and copies a block of memory == RGB values). But is there a price to pay (at least in Windows world) where and there obscuring the window also get copied. I don’t notice this as I process on hpc (so I don’t have to copy files back and forward) where I start the export nc thing and don’t do anything else on the hpc (but for me I can minimize my connection to hpc and it doesn’t affect the figure). On Windows so would have to start the process and not doing anything on the machine. Figures generated from our imos-datatools code uses the slow way for this reason.
> 
> One other (possible) consequence of using fast method it that on Windows, working out the correct region to clip (copy memory part) isn’t easy, hence the bit at the bottom of the pic with taskbar.
> 
> ...
> 
> Think the main one would have been the introduction of screencapture in fastSaveas.m (the fast why of saving images).
> 
> As another test, I compiled up a version where I used export_fig code (as per imos-datatools).

This fix of changing the code to 'export_fig_code' ended up working, but I guess it's been changed again in one of the recent updates.

**Comment by ggalibert** [comment]
All of the above is correct and I would add for completeness that screencapture had been introduced to help producing consistent file printed plots across platforms. Even though what you'd see in Linux and Windows are pretty similar, the file printed plots produced in the past would be inconsistent (font wise in particular). 

I'm aware that file printing plots is also an issue for re-processing in the background (figures keep popping up so it's difficult to work on something else in the meantime). So I would like to investigate other file printing solutions, even going back to native Matlab (if I can have consistent results across platforms) and assess the cost in extra CPU time. It would also be interesting to know how Matlab versions higher than 2015b (major graphing re-development) behaves.

**Comment by ggalibert** [comment]
@mrbeck85 and @sspagnol could you please provide me with this ```export_fig``` code so that I can have a look?

**Comment by mrbeck85** [comment]
I was using v2016, I think 2016b, for his mooring. I went back to images I processed last week and they look like this:

![imos_anmn-qld_gbrote_fv01_gbrote-1410_line_cphl_c-20170704t033131z](https://user-images.githubusercontent.com/22756976/28049197-04e5932c-6639-11e7-99b5-fed8c63ed6ad.png)

As you said, doing anything else while the toolbox is generating/saving images causes a problem. 

When Simon instituted his fix back in February the processing time for each image only increased by ~2-3 seconds (Simon the email I originally sent was titled "Toolbox Image Generation", sometime around 6/2/2017). The time tradeoff when you're only generating about a dozen images every time you export a NetCDF from the toolbox doesn't seem too bad, in exchange for making sure all of the plot is guaranteed to be in the final saved image. The inconsistency in font between operating systems is a problem I'm unfamiliar with though.

**Comment by ggalibert** [comment]
For information and background on this, the original issue that motivated moving toward screen capture was the following: https://github.com/aodn/imos-toolbox/issues/373

**Comment by ggalibert** [comment]
Commits https://github.com/aodn/imos-toolbox/commit/ca1020c6e4a036d83a1e8d8bd40f1c3c293f7868 and https://github.com/aodn/imos-toolbox/commit/53f39974a13e01dd1cd75959f193dca2eef73129 implemented in [v2.5.30](https://github.com/aodn/imos-toolbox/releases/tag/v2.5.30) should fix the issue. 

@mrbeck85, @anaredd and others affected please [pull the changes from branch 2.5](https://github.com/aodn/imos-toolbox/wiki/ToolboxInstallation#install-imos-toolbox) to get to v2.5.30 in order to validate this fix. If the same problem subsists please re-open this issue.
