### ISSUE TITLE
New SeaBird code for Chlorophyl-a

### ISSUE THREAD

**Issue by ggalibert** [aodn/imos-toolbox#550]
In the .cnv file, a new code header for chlorophyl-a `flCUVA` has been introduced and is currently not supported. `convertSBEcnvVar` needs to be updated accordingly.

**Comment by ggalibert** [comment]
Example file [CJ01cafld.cnv.zip](https://github.com/aodn/imos-toolbox/files/3259637/CJ01cafld.cnv.zip).

**Comment by anaredd** [comment]
Same for the PAR data (par/sat/log from the PAR/Logarithmic, Satlantic)

**Comment by ocehugo** [comment]
My understanding so far:

1. A new key ```flCUVA``` appears in the header file of SBE19Plus.
2. This key is missing processing when calling SBE19Parse
3. The same occurs for ```par/sat/log```.

This is straight forward but to complete the PR I need more information:

1. flCUVA should map to ```chpl```!? A quick search pointed me that the sensor Chelsea UV aquatracka 
is for CDOM/Hydrocarbon, if so, this need to be regressed against something for the conversion before naming it as Chla.
2. What the comment should be?
3. Same of the above for par/sat/log. Should it be a specific entry or just another case of ```PAR```?

Questions:
1. why these mappings are not carrying over the actual sensor name within the SBE insturment? 
2. Why the units are not carry over? I can see conversions being done on the fly instead of first loading the actual data from the headers
3. Which reference for "instrument names, units, conversion rules" should I use? These bits are within the code itself or there is a proper "global table"?


Requirements:

- [x] A new case entry for 1 and 3 above is required in ```convertSBEcnvVar```
- [ ] instrument.var -> toolbox.var names are correct for both variables
- [ ] toolbox.var comments is correct for both variables
- [ ] A proper reference is made for whatever conversion is done or will be done.

**Comment by ocehugo** [comment]
Also, what should be in wiki afterwards?

**Comment by anaredd** [comment]
@ocehugo 
The variable flCUVA refers to chlorophyll concentration (in ug/L) from the Aquatacka MKIII fluorometer, where the chlorophyll has been calculated using the factory calibration coefficients (calibration performed on June 2018 in the example above). So no, no need to convert any further or add other comments.
 
Same goes for the PAR data, which outputs the PAR in umol photons/m2/s

**Comment by ocehugo** [comment]
Thanks @anaredd 

@ggalibert, the Aquatracka and PARlog sensor got calibration dates and coefficients within the cnv file. Should I implement something to add this to the comment?

I think it's better to add something in the comments, but I may be wrong - See PR#572

**Comment by petejan** [comment]
This https://github.com/petejan/imos-toolbox/blob/SBEddParser/Parser/SBEcnvParse.m is an attempt to do that more generally. Along with the file https://github.com/petejan/imos-toolbox/blob/SBEddParser/Parser/seabirdNames.xlsx makes it easy to add names from new sea bird parameters.

**Comment by ggalibert** [comment]
> the Aquatracka and PARlog sensor got calibration dates and coefficients within the cnv file. Should I implement something to add this to the comment?

Not yet, this is not in the scope of this issue. There is a separate issue to deal with coefficient calibration. In addition, there will be a meeting later in August/September to talk about this particular issue and decide for a solution that could be applied to all instruments processed by the toolbox.

**Comment by ocehugo** [comment]
> This https://github.com/petejan/imos-toolbox/blob/SBEddParser/Parser/SBEcnvParse.m is an attempt to do that more generally. Along with the file https://github.com/petejan/imos-toolbox/blob/SBEddParser/Parser/seabirdNames.xlsx makes it easy to add names from new sea bird parameters.

I agree, the parsers/readers are too chatty, big and more importantly, they do the same thing with only slightly different regex bits.  An even more generic structure can be possible (for example, the regex should be inputted instead of defined within the function). 

The problem with a refactoring right now is that I'm not versed enough in the toolbox mechanics and there are minimal tests. Otherwise, we risk breakage or wrongdoings. We have to first provide tests before doing strong refactoring, but this milestone is the priority at the moment. 
 
> Not yet, this is not in the scope of this issue. There is a separate issue to deal with coefficient calibration. In addition, there will be a meeting later in August/September to talk about this particular issue and decide for a solution that could be applied to all instruments processed by the toolbox.

Ok, I'm mentioning #301, so we can track the stuff related to it
