### ISSUE TITLE
Q: should test data be moved to seperate repository?

### ISSUE THREAD

**Issue by sspagnol** [aodn/imos-toolbox#559]
Just a question if we start stuffing test data into imos-toolbox repo, it could get large quickly.

**Comment by petejan** [comment]
I would create a small sample test file in the repo for testing a parser, which is what I did in the test directory.

**Comment by ocehugo** [comment]
Requirements:
- [ ] Define what to do with the test files
- [ ] Overview and a quick test of alternative options (LFS, git-bigstore, etc)
- [ ] Define and document hierarchy rules and usage auth required.
- [ ] Update code to support the implemented extension if so.
- [ ] Update documentation (provide guidance or allow users to obtain the test data).

--
ATM, a lot of files are already kept out of the tree.  For example, @ggalibert got a big chunk of extra folders. However, some files are in the tree.

I agree, and my view is that only files required to run the toolbox should be within the repo. That's why I didn't include the data in #561. 

It is a bit of pain first since we have to manage two different things, but there are extensions to help us to keep a seamless experience (e.g. 1. git lfs, 2. git-bigstore).

For example, I would use 1. for 3 reasons: It's relatively easy to set up and use, GitHub supports it out of the box, and we already got some allowance (AFAIK). In any case, we could set up both to use AODN aws infrastructure.

I would also point out that, in testing, output files should also be maintained. A bisect on the file differences would then be possible. This could be as easier as running a simple command if we are careful enough (e.g. avoid storing creation times in filenames and within netcdfs for these output test files).

Finally, I would vote to create a data folder, mimicking the actual repo: eg the current Test/oxygenPP folder would be moved to data/Tests/ncParser/oxygenPP_cnv. The folder can then be ignored in git and those pesky ppp files (and any tmp ones) would stop polluting the git status.

**Comment by ocehugo** [comment]
We had some recent changes regarding this:

git-lfs was abandoned given we don't have more quota on github, it's more expensive than aws, and it's bandwidth-limited (not optimal for public repos like this). Hence, test files will be hosted by aodn in aws.  A script is provided in the case users need to download the files to run the tests in imos-toolbox/Test folder.

**Comment by ocehugo** [comment]
We moved recent testfiles to imos_toolbox/data/testfiles.
We got the following structure:
```
imos_toolbox/data/testfiles/ 
                                           [Manufacturer]/[InstrumentName]/[version]
```

or (for different formats)
``` 
imos_toolbox/data/testfiles/ 
                                           [Manufacturer]/[InstrumentName]/[format]/[version] 
```

or (for checking against a reference in .mat)

```
imos_toolbox/data/testfiles/ 
                                           [Manufacturer]/[InstrumentName]/[format]/[version]/mat
```

The only missing bit on this issue is that current folders under "test" need to be migrated for consistency.

Requirements:

- [ ] update previous code in "test" to read files in the test folders
- [ ] move instrument files to the correct folders

**Comment by ocehugo** [comment]
See https://github.com/aodn/imos-toolbox/wiki/UnitTests
