### ISSUE TITLE
2.6.1 version number query

### ISSUE THREAD

**Issue by sspagnol** [aodn/imos-toolbox#605]
Should this line
https://github.com/aodn/imos-toolbox/blob/40287a2ddbe7c71435fd52629db9538afbd4aad1/imosToolbox.m#L40

say '2.6.1' instead?

**Comment by testGali** [comment]
Yes it should. @ocehugo can this be fixed please? It is important as it is displayed on the UI and output as an attribute in any NetCDF produced with the toolbox so that we can identify which version of the toolbox has been used.

**Comment by ocehugo** [comment]
Sorry guys, clearly I forgot that bit. 

I'm creating a quickfix will report back when merged.

**Comment by ocehugo** [comment]
Fixed.

master is updated, as well as branch 2.6:

```
git fetch
git checkout 2.6
git pull
```

**Comment by ocehugo** [comment]
Reopening: c6c0f20ccc9cf6779b12a688b6b453e36bbe6d46 didn't update the binaries. Sorry about that guys, but I will need to make a new release. 

We also got an important hot-fix (#608) that should be included too.

**Comment by ocehugo** [comment]
See release 2.6.3 https://github.com/aodn/imos-toolbox/releases

**Comment by ocehugo** [comment]
sorry bothering all again about this, but I had to abort the 2.6.3 tag release since I wrongly copied the binaries into the repo. Since I already tagged it, I can't roll back (I can't rewrite history here on master). We will have to "forget" the 2.6.3 tag and go straight to 2.6.4.

Just wait for a new release email or when the tag is present in the repo for a checkout on the 2.6 branch.
