### ISSUE TITLE
Starmon header error with updated parser

### ISSUE THREAD

**Issue by BecCowley** [aodn/imos-toolbox#633]
@ocehugo, I have an error as the date format has a different field separator:

Warning: Using the old StarmonMiniParse. Please raise an issue in our github page with this warning
msg: Could not define date based on input dd.mm.yyyy	. 
> In StarmonMiniParse (line 42)
  In importManager>ddbImport/parse (line 441)
  In importManager>ddbImport (line 362)
  In importManager (line 76)
  In flowManager (line 39)
  In imosToolbox (line 74) 

This is the line in the header file:
#7	Date def.:	dd.mm.yyyy	.

**Comment by kereid** [comment]
Hi @BecCowley, Thank you for reporting this. @ocehugo is on leave until next week so he won't be able to resolve or advise until then - just so you know why there won't be a response this week :-).  Warm regards, Kate.

**Comment by ocehugo** [comment]
Hi @BecCowley,

Thanks for reporting this. The problem here is a lack of coverage of new options since there is no reference for the new Staroddi software exported fields.

I'll soon add a fix for your case, but if you can put the file here (or send to my email), it would be a great addition to our test coverage (otherwise I have to fake one, and I may miss some other different field option).

If you are in a rush, the quickest pathway here is to change the output format in the seastar software computer to use dates with ```/``` instead of ```.``` - this is already supported.

**Comment by BecCowley** [comment]
Will send the file to your email.
